# Generated by Django 2.0 on 2018-07-17 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('last_updated', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('star_rating', models.IntegerField()),
                ('previous_star_rating', models.IntegerField(blank=True, null=True)),
                ('shop_domain', models.TextField()),
                ('shop_name', models.TextField()),
                ('created_at', models.TextField()),
                ('updated_at', models.TextField(blank=True, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data_viewer.App')),
            ],
        ),
    ]
